stages:
  - setup
  - lint
  - testing
  - deploy

include:
  - local: .gitlab/ci/setup.gitlab-ci.yml
  - local: .gitlab/ci/lint.gitlab-ci.yml
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/deploy.gitlab-ci.yml