build tsc:

  stage: build
  image: node:13

  script:
    - yarn build

  dependencies:
    - prepare
    - lint
    - unit tests

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - src
        - tests/**
        - .gitlab-ci.yml
        - .gitlab/**
        - yarn.lock
        - jest.config.js
        - package.json
        - tsconfig.json
        - .eslintrc.js
        - .prettierrc.js
      when: on_success