lint:

  stage: lint
  image: node:13

  script:
    - yarn lint

  dependencies:
    - prepare

  cache:
    key: "$CI_COMMIT_SHA"
    policy: pull

  rules:
    - changes:
      - src
      - tests/**
      - .gitlab-ci.yml
      - .gitlab/**
      - yarn.lock
      - jest.config.js
      - package.json
      - tsconfig.json
      - .eslintrc.js
      - .prettierrc.js
    - when: on_success